trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  name: Default
  demands: LabVIEW

variables:
  libssh2.version: '1.11.1'
  libssh2.commit: 'a312b43325e3383c865a87bb1d26cb52e3292641'
  openssl.version: '3.4.1'
  openssl.commit: 'a26d85337dbdcd33c971f38eb3fa5150e75cea87'

strategy:
  matrix:
    'x86-win-openssl-debug':
      architecture: 'Win32'
      backend: 'OpenSSL'
      config: 'Debug'
    'x86-win-openssl-release':
      architecture: 'Win32'
      backend: 'OpenSSL'
      config: 'Release'

steps:
- task: CmdLine@2
  displayName: 'Prepare build configurations'
  inputs:
    script: cmake -B build/$(architecture) -S . -G "Visual Studio 17 2022" -A $(architecture) -DLIBSSH2_SOURCE=GitHub -DLIBSSH2_COMMIT_HASH=$(libssh2.commit) -DCRYPTO_BACKEND=$(backend) -DOPENSSL_COMMIT_HASH=$(openssl.commit)
    workingDirectory: '$(Build.SourcesDirectory)'
- task: CmdLine@2
  displayName: 'Build libraries'
  inputs:
    script: cmake --build build/$(architecture) --config $(config)
    workingDirectory: '$(Build.SourcesDirectory)'
- script: docker compose up -d --force-recreate
  displayName: 'Start SSH server'
  workingDirectory: '$(Build.SourcesDirectory)/docker'
- task: CmdLine@2
  displayName: 'Restore packages'
  inputs:
    script: 'LabVIEWCLI -LabVIEWPath "%LabVIEW%\LabVIEW.exe" -AdditionalOperationDirectory "$(Build.SourcesDirectory)\Toolchain" -OperationName Restore -Configuration "$(Build.SourcesDirectory)\lvssh2-dev.vipc"'
    workingDirectory: '$(Build.SourcesDirectory)'
- task: CmdLine@2
  displayName: 'Run tests'
  inputs:
    script: 'LabVIEWCLI -LabVIEWPath "%LabVIEW%\LabVIEW.exe" -AdditionalOperationDirectory "$(Build.SourcesDirectory)\Toolchain" -OperationName Test -Project "$(Build.SourcesDirectory)\lvssh2.lvproj" -ResultsFolder "$(System.DefaultWorkingDirectory)\TestResults"'
    workingDirectory: '$(Build.SourcesDirectory)'
- script: docker compose down
  displayName: 'Stop SSH server'
  workingDirectory: '$(Build.SourcesDirectory)/docker'
- publish: '$(System.DefaultWorkingDirectory)/docker/openssh-server/config/logs/openssh/current'
  displayName: 'Publish SSH server logs'
  artifact: server-log-($(Agent.JobName))
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
