trigger:
- '*'

pool:
  name: Default
  demands: LabVIEW

strategy:
  matrix:
    'libssh2-1.11.1-x86':
      architecture: 'Win32'
      source: 'GitHub'
      commit: 'a312b43325e3383c865a87bb1d26cb52e3292641'
      config: 'Debug'

steps:
- task: CmdLine@2
  displayName: 'Prepare build configurations'
  inputs:
    script: cmake -B build/$(architecture) -S . -G "Visual Studio 17 2022" -A $(architecture) -DLIBSSH2_SOURCE=$(source) -DLIBSSH2_COMMIT_HASH=$(commit)
    workingDirectory: '$(Build.SourcesDirectory)'
- task: CmdLine@2
  displayName: 'Build libraries'
  inputs:
    script: cmake --build build/$(architecture) --config $(config)
    workingDirectory: '$(Build.SourcesDirectory)'
- script: docker compose up -d --force-recreate
  displayName: 'Start SSH server'
  workingDirectory: '$(Build.SourcesDirectory)/docker'
- task: CmdLine@2
  displayName: 'Restore packages'
  inputs:
    script: 'LabVIEWCLI -LabVIEWPath "%LabVIEW%\LabVIEW.exe" -AdditionalOperationDirectory "$(Build.SourcesDirectory)\Toolchain" -OperationName Restore -Configuration "$(Build.SourcesDirectory)\lvssh2-dev.vipc"'
    workingDirectory: '$(Build.SourcesDirectory)'
- task: CmdLine@2
  displayName: 'Run tests'
  inputs:
    script: 'LabVIEWCLI -LabVIEWPath "%LabVIEW%\LabVIEW.exe" -AdditionalOperationDirectory "$(Build.SourcesDirectory)\Toolchain" -OperationName Test -Project "$(Build.SourcesDirectory)\lvssh2.lvproj" -ResultsFolder "$(System.DefaultWorkingDirectory)\TestResults"'
    workingDirectory: '$(Build.SourcesDirectory)'
- script: docker compose down
  displayName: 'Stop SSH server'
  workingDirectory: '$(Build.SourcesDirectory)/docker'
- publish: '$(System.DefaultWorkingDirectory)/docker/openssh-server/config/logs/openssh/current'
  displayName: 'Publish SSH server logs'
  artifact: SSH server logs
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
